In [2]:
import numpy as np

### 多维数组及其属性

#### 生成多维数组

In [3]:
a = np.array([[2,3,4],[5,6,7]])
a

array([[2, 3, 4],
       [5, 6, 7]])

查看形状

In [5]:
a.shape

(2, 3)

查看元素总个数

In [6]:
a.size

6

#### 多维数组索引

In [8]:
a[1,1]

6

In [9]:
# 对数组内容进行赋值
a[1,1] = 100

In [10]:
a

array([[  2,   3,   4],
       [  5, 100,   7]])

In [11]:
# 获取到某行所有元素
a[1]

array([  5, 100,   7])

In [12]:
# 可以得到第二列的所有元素
a[:,1]

array([  3, 100])

#### 多维数组切片

In [18]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14]])

得到第一行的第4和第5两元素

In [17]:
a[0,3:]

array([4, 5])

得到最后两行的最后两列

In [19]:
a[1:,3:]

array([[ 9, 10],
       [13, 14]])

取出 1 3行的奇数列

In [20]:
a[::2,::2]

array([[ 1,  3,  5],
       [10, 12, 14]])

#### 列表和数组在切片上的差异
对于数组，切片使用的是引用机制，这意味着 如果 b = a[1:2] ，python 并没有为b分配新内存空间，而是让b指向了a所分配的内存空间
但是对于列表则不是使用引用机制

- 这样的好处是： 对于很大的数组，不用复制多余的值，节约了空间
- 可能出现数据错误

为了解决可能会造成数据改动的情况，可以使用copy()方法来产生一个复制，这个复制会申请新的内存：

In [21]:
a = np.array([2,3,4,5])
b = a[2:4].copy()
b[0] = 99
a

array([2, 3, 4, 5])