In [2]:
import numpy as np

In [3]:
np.__version__

'1.16.4'

In [4]:
np.show_config

<function numpy.__config__.show()>

In [5]:
data = np.zeros(10,dtype="int")
data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

要求数组中元素的个数：data.size
要求数组中元素所占的字节数：data.itemsize

In [6]:
data.size,data.itemsize

(10, 4)

#### 如何从命令行中得到numpy中add函数的说明文档

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [8]:
data = np.zeros(10)
data[4] = 1
data

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [9]:
data = np.arange(10,50)
data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 反转一个向量

In [10]:
data = np.arange(50)
data = data[::-1]
data

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 创建一个3x3并且值从0到8的矩阵

In [11]:
data = np.arange(9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 找到数组[1,2,0,0,4,0]中非0元素的位置索引 

In [12]:
data = np.nonzero([1,2,0,0,4,0])
data

(array([0, 1, 4], dtype=int64),)

#### 创建一个3x3的单位矩阵

In [13]:
data = np.eye(3)
data

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
data = np.random.random((3,3,3,))
data

array([[[2.53000506e-01, 3.08681447e-01, 3.79747096e-01],
        [3.54064847e-01, 9.61109154e-01, 1.20083179e-01],
        [3.25702923e-01, 8.95261248e-01, 4.43213389e-01]],

       [[7.25262252e-01, 3.75416368e-01, 4.46794271e-04],
        [6.28485419e-01, 4.03359535e-01, 8.26411061e-01],
        [6.37204764e-01, 2.18520588e-01, 7.40176384e-01]],

       [[2.23115072e-01, 7.98615976e-01, 1.76660910e-01],
        [4.17401347e-01, 3.68276482e-01, 7.38816533e-01],
        [8.85390285e-01, 2.67135665e-02, 8.65295868e-01]]])

#### 创建一个10x10的随机数组并且找到其最大值和最小值

In [17]:
data = np.random.random((10,10))
dataMax,dataMin = data.max(),data.min()
dataMax,dataMin

(0.9966077437006036, 0.008138396012387306)

#### 创建一个长度为30的随机向量并找到他的平均值

In [18]:
data = np.random.random(30)
m = data.mean()
m

0.5000627126613635

#### 创建一个二维数组，其中边界值为1，其余值为0

In [22]:
# data = np.zeros((10,10))
# data[0] = 1
# data[-1] = 1
# data[:,0] = 1
# data[:,-1] = 1
# data
data = np.ones((10,10))
data[1:-1,1:-1] = 0
data

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 对于一个存在在数组，如何添加一个用0填充的边界?

In [23]:
data = np.ones((10,10))
data = np.pad(data,pad_width=1,mode='constant',constant_values=0)
data
# 详细介绍：https://blog.csdn.net/hustqb/article/details/77726660

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 以下表达式运行的结果分别是什么?

In [24]:
0*np.nan

nan

In [25]:
np.nan == np.nan

False

In [26]:
np.inf > np.nan

False

In [27]:
np.nan - np.nan

nan

In [30]:
0.3 == 3 * 0.1

False

#### 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 

In [31]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)
'''
关于 np.diag 的使用
>>> x = np.arange(9).reshape((3,3))
>>> x
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
>>>
>>> np.diag(x)
array([0, 4, 8])
>>> np.diag(x, k=1)
array([1, 5])
>>> np.diag(x, k=-1)
array([3, 7])
>>>
>>> np.diag(np.diag(x))
array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])
'''

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [33]:
data = np.arange(0,9).reshape(3,3)+2
data

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [34]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [35]:
 print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [37]:
np.info(np.unravel_index)
'''
其中 unravel_index(indices, shape, order='C') 的作用是返回indices 中的元素在 shape的
'''

unravel_index(indices, shape, order='C')

Converts a flat index or array of flat indices into a tuple
of coordinate arrays.

Parameters
----------
indices : array_like
    An integer array whose elements are indices into the flattened
    version of an array of dimensions ``shape``. Before version 1.6.0,
    this function accepted just one index value.
shape : tuple of ints
    The shape of the array to use for unraveling ``indices``.

    .. versionchanged:: 1.16.0
        Renamed from ``dims`` to ``shape``.

order : {'C', 'F'}, optional
    Determines whether the indices should be viewed as indexing in
    row-major (C-style) or column-major (Fortran-style) order.

    .. versionadded:: 1.6.0

Returns
-------
unraveled_coords : tuple of ndarray
    Each array in the tuple has the same shape as the ``indices``
    array.

See Also
--------
ravel_multi_index

Examples
--------
>>> np.unravel_index([22, 41, 37], (7,6))
(array([3, 6, 6]), array([4, 5, 1]))
>>> np.unravel_index([31, 41, 1

In [57]:
# a = [2,3,4,5,6,7,8,1,12,23,34,55]
# b = np.array(a).reshape((3,4))
# np.unravel_index(7,(3，4))
np.unravel_index(7, (3,4),order='F')

(1, 2)

#### 用tile函数去创建一个 8x8的棋盘样式矩阵

In [63]:
data = np.tile(np.array([[0,1],[1,0]]),(4,4))
data

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 对一个5x5的随机矩阵做归一化
所谓归一化处理就是 (value - valueMin)/(valueMax - valueMin)

In [65]:
data = np.random.random((5,5))
dataMin,dataMax = data.min(),data.max()
data = (data - dataMin)/(dataMax - dataMin)
data

array([[0.        , 0.74868299, 0.40494956, 0.79955127, 0.20378641],
       [0.10836631, 0.42085621, 0.78210663, 0.28159138, 0.03184626],
       [0.71877071, 0.07726668, 0.12100316, 0.143051  , 0.122301  ],
       [0.30048312, 0.10031864, 1.        , 0.19366011, 0.82679278],
       [0.16327237, 0.47004516, 0.32658441, 0.70261914, 0.63274147]])

In [69]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 给定一个一维数组，对其在3到8之间的所有元素取反

In [70]:
data = np.arange(11)
data[(3<data) & (data<=8)] *= -1
data

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 考虑一个整数向量Z,下列表达合法的是哪个?

In [97]:
data = np.arange(5)
data**data

array([  1,   1,   4,  27, 256], dtype=int32)

In [117]:
Z = np.arange(5)
Z == Z

array([ True,  True,  True,  True,  True])

In [129]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ -4.  -8.  -3.   2. -10.   7.  -8.   7.  -1.  -3.]


#### 如何找到两个数组中的共同元素?

In [172]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[5 6 8 9]


In [175]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-07
Today is 2019-08-08
Tomorrow is 2019-08-09
